#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef X3UI_SWIFT_H
#define X3UI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="x3UI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, ControlEventDataType, open) {
  ControlEventDataTypeNone = -1,
  ControlEventDataTypeBool = 1,
  ControlEventDataTypeInt = 2,
  ControlEventDataTypeString = 3,
  ControlEventDataTypeEnumiratedString = 4,
  ControlEventDataTypeObject = 21,
};


SWIFT_PROTOCOL("_TtP4x3UI20ControlEventDelegate_")
@protocol ControlEventDelegate
@optional
- (void)controlEvent:(id _Nullable)sender event:(id _Nullable)event;
@end

@class NSLayoutConstraint;

@interface NSLayoutAnchor<AnchorType> (SWIFT_EXTENSION(x3UI))
- (NSLayoutConstraint * _Nonnull)constraintWithEqualTo:(NSLayoutAnchor<AnchorType> * _Nonnull)anchor constant:(CGFloat)c isActive:(BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
@end


@class Drawing;
@class Animating;

SWIFT_CLASS("_TtC4x3UI18ToolTipPreferences")
@interface ToolTipPreferences : NSObject
@property (nonatomic, strong) Drawing * _Nonnull drawing;
@property (nonatomic, strong) Animating * _Nonnull animating;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Arrow;
@class Bubble;
@class Title;
@class Message;
@class Button;
@class Background;

SWIFT_CLASS("_TtCC4x3UI18ToolTipPreferences7Drawing")
@interface Drawing : NSObject
@property (nonatomic, strong) Arrow * _Nonnull arrow;
@property (nonatomic, strong) Bubble * _Nonnull bubble;
@property (nonatomic, strong) Title * _Nonnull title;
@property (nonatomic, strong) Message * _Nonnull message;
@property (nonatomic, strong) Button * _Nonnull button;
@property (nonatomic, strong) Background * _Nonnull background;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing5Arrow")
@interface Arrow : NSObject
@property (nonatomic) CGSize size;
@property (nonatomic) CGFloat tipCornerRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class Border;

SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing6Bubble")
@interface Bubble : NSObject
@property (nonatomic) CGFloat inset;
@property (nonatomic) CGFloat spacing;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat maxWidth;
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull gradientLocations;
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull gradientColors;
@property (nonatomic, strong) Border * _Nonnull border;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCCC4x3UI18ToolTipPreferences7Drawing6Bubble6Border")
@interface Border : NSObject
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic) CGFloat width;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;

SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing5Title")
@interface Title : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing7Message")
@interface Message : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing6Button")
@interface Button : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing10Background")
@interface Background : NSObject
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC4x3UI18ToolTipPreferences9Animating")
@interface Animating : NSObject
@property (nonatomic) CGAffineTransform dismissTransform;
@property (nonatomic) CGAffineTransform showInitialTransform;
@property (nonatomic) CGAffineTransform showFinalTransform;
@property (nonatomic) CGFloat springDamping;
@property (nonatomic) CGFloat springVelocity;
@property (nonatomic) CGFloat showInitialAlpha;
@property (nonatomic) CGFloat dismissFinalAlpha;
@property (nonatomic) NSTimeInterval showDuration;
@property (nonatomic) NSTimeInterval dismissDuration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@class NSString;
enum ArrowPosition : NSInteger;
@protocol UIX3ToolTipDelegate;

@interface UIBarItem (SWIFT_EXTENSION(x3UI))
- (void)showToolTipWithIdentifier:(NSString * _Nonnull)identifier title:(NSString * _Nullable)title message:(NSString * _Nonnull)message button:(NSString * _Nullable)button arrowPosition:(enum ArrowPosition)arrowPosition preferences:(ToolTipPreferences * _Nonnull)preferences delegate:(id <UIX3ToolTipDelegate> _Nullable)delegate;
@end


@class NSCoder;

SWIFT_CLASS("_TtC4x3UI29UIBaseNavigationBarButtonItem")
@interface UIBaseNavigationBarButtonItem : UIBarButtonItem
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4x3UI26UIBaseNavigationTitleLabel")
@interface UIBaseNavigationTitleLabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4x3UI25UIBaseNavigationTitleView")
@interface UIBaseNavigationTitleView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end













@interface UIView (SWIFT_EXTENSION(x3UI))
- (void)showToolTipWithIdentifier:(NSString * _Nonnull)identifier title:(NSString * _Nullable)title message:(NSString * _Nonnull)message button:(NSString * _Nullable)button arrowPosition:(enum ArrowPosition)arrowPosition preferences:(ToolTipPreferences * _Nonnull)preferences delegate:(id <UIX3ToolTipDelegate> _Nullable)delegate;
@end

@class UIViewController;

@interface UIView (SWIFT_EXTENSION(x3UI))
@property (nonatomic, readonly, strong) UIViewController * _Nullable parentViewController;
@end





SWIFT_CLASS("_TtC4x3UI12UIViewBorder")
@interface UIViewBorder : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIViewController (SWIFT_EXTENSION(x3UI))
+ (nonnull instancetype)fromNib SWIFT_WARN_UNUSED_RESULT;
@end

@class UIAlertAction;
@class UITextField;
@class UIAlertController;

@interface UIViewController (SWIFT_EXTENSION(x3UI))
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle handler:(void (^ _Nullable)(UIAlertAction * _Nonnull))handler;
- (void)showYesNoAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message yesTitle:(NSString * _Nonnull)yesTitle noTitle:(NSString * _Nonnull)noTitle yesHandler:(void (^ _Nullable)(UIAlertAction * _Nonnull))yesHandler noHandler:(void (^ _Nullable)(UIAlertAction * _Nonnull))noHandler;
- (void)showAlertWithTextFieldWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message textFieldConfiguration:(void (^ _Nullable)(UITextField * _Nonnull))textFieldConfiguration confirmButtonTitle:(NSString * _Nonnull)confirmButtonTitle handler:(void (^ _Nonnull)(UIAlertController * _Nullable))handler;
- (void)showPopover:(UIViewController * _Nonnull)viewController sourceRect:(CGRect)sourceRect with:(CGSize)size direction:(UIPopoverArrowDirection)direction;
- (void)showPopover:(UIViewController * _Nonnull)viewController barButton:(UIBarButtonItem * _Nonnull)barButton with:(CGSize)size direction:(UIPopoverArrowDirection)direction;
@end

@class NSBundle;

IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI23UIX3AlertViewController")
@interface UIX3AlertViewController : UIViewController
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLayoutSubviews;
- (void)dismissAlertView;
@end

@class UX3CustomButton;

SWIFT_PROTOCOL("_TtP4x3UI31UIX3AlertViewControllerDelegate_")
@protocol UIX3AlertViewControllerDelegate
@optional
- (void)alertViewWithSender:(UIX3AlertViewController * _Nonnull)sender buttonType:(NSInteger)buttonType buttonCreate:(UX3CustomButton * _Nullable)buttonCreate;
- (void)alertViewWithSender:(UIX3AlertViewController * _Nonnull)sender buttonType:(NSInteger)buttonType buttonClick:(UX3CustomButton * _Nullable)buttonClick;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI13UIX3TextField")
@interface UIX3TextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
- (void)textFieldDidChange;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)rightViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)leftViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)drawTextInRect:(CGRect)rect;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI20UIX3CaptionTextField")
@interface UIX3CaptionTextField : UIX3TextField
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI14UIX3CustomView")
@interface UIX3CustomView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI15UIX3CaptionView")
@interface UIX3CaptionView : UIX3CustomView
- (void)layoutSubviews;
@property (nonatomic, copy) IBInspectable NSString * _Nullable caption;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable font;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIX3CaptionView (SWIFT_EXTENSION(x3UI)) <UITextViewDelegate>
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI20UIX3CustomBorderView")
@interface UIX3CustomBorderView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI22UIX3CustomBorderedView")
@interface UIX3CustomBorderedView : UIView
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITraitCollection;

IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI24UIX3CustomViewController")
@interface UIX3CustomViewController : UIViewController
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull backgroundColor;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (void)deviceRotateEventWithOrientation:(UIDeviceOrientation)orientation isLandscape:(BOOL)isLandscape;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP4x3UI32UIX3CustomViewControllerDelegate_")
@protocol UIX3CustomViewControllerDelegate
@optional
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender;
- (void)customViewControllerWithWillSetupFor:(UIX3CustomViewController * _Nonnull)sender;
- (NSString * _Nonnull)customViewControllerWithTitleFor:(UIX3CustomViewController * _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender keyboardRect:(id _Nullable)keyboardRect duration:(double)duration options:(id _Nullable)options;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender keyboardTopPosition:(CGFloat)keyboardTopPosition duration:(double)duration options:(id _Nullable)options;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender statusBarStyle:(UIStatusBarStyle)statusBarStyle;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender orientation:(UIDeviceOrientation)orientation isLandscape:(BOOL)isLandscape;
@end

@class NSTextContainer;
@class NSAttributedString;
@class UIImage;

/// Text field with support for multiple lines.
/// note:
/// Under the hood this is just a <code>UITextView</code> which aims to provide
/// many of the functionalities currently available in the <code>UITextField</code> class.
/// Currently the following functionalities are supported:
/// <ul>
///   <li>
///     Multiple lines
///   </li>
///   <li>
///     Customizable left view
///   </li>
///   <li>
///     Customizable placeholder
///   </li>
/// </ul>
/// todo:
/// The following features are still missing:
/// <ul>
///   <li>
///     Add support for displaying a right view
///   </li>
///   <li>
///     Configure when left/right views will be shown using <code>UITextField.leftViewMode</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC4x3UI22UIX3MultilineTextField")
@interface UIX3MultilineTextField : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic, strong) NSAttributedString * _Null_unspecified attributedText;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
/// Convenience property to set an image directly instead of a left view
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftImage;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end

@class UIGestureRecognizer;

SWIFT_CLASS("_TtC4x3UI18UIX3SegmentControl")
@interface UIX3SegmentControl : UISegmentedControl
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable tintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable foregroundColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable font;
- (void)layoutSubviews;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI12UIX3TextView")
@interface UIX3TextView : UIX3CustomView <UITextViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable textColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable placeholderTextColor;
@property (nonatomic, strong) IBInspectable UIColor * _Null_unspecified tintColor;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftButtonImage;
@property (nonatomic) IBInspectable CGFloat leftButtonImageOffset;
@property (nonatomic) IBInspectable CGFloat leftButtonLeftOffset;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable rightButtonImage;
@property (nonatomic) IBInspectable CGFloat rightButtonImageOffset;
@property (nonatomic) IBInspectable CGFloat rightButtonRightOffset;
@property (nonatomic, copy) IBInspectable NSString * _Nullable text;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
- (void)layoutSubviews;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
@end


SWIFT_CLASS("_TtC4x3UI11UIX3ToolTip")
@interface UIX3ToolTip : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, ArrowPosition, open) {
  ArrowPositionTop = 0,
  ArrowPositionRight = 1,
  ArrowPositionBottom = 2,
  ArrowPositionLeft = 3,
};


SWIFT_PROTOCOL("_TtP4x3UI19UIX3ToolTipDelegate_")
@protocol UIX3ToolTipDelegate
- (void)toolTipViewDidAppearFor:(NSString * _Nonnull)identifier;
- (void)toolTipViewDidDisappearFor:(NSString * _Nonnull)identifier with:(NSTimeInterval)timeInterval;
@end


SWIFT_CLASS("_TtC4x3UI11UIX3XibView")
@interface UIX3XibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI15UX3CustomButton")
@interface UX3CustomButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalForegroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalBorderColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedForegroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedBorderColor;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI16UX3RoundedButton")
@interface UX3RoundedButton : UIButton
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull normalColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI25UX3SliderIndicatorControl")
@interface UX3SliderIndicatorControl : UIControl
@property (nonatomic) IBInspectable CGFloat animationDuration;
@property (nonatomic) IBInspectable CGFloat thumbViewAlpha;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull segmentColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull thumbColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull segmentSelectedColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP4x3UI22UX3TextControlDelegate_")
@protocol UX3TextControlDelegate
@optional
- (void)UX3TextControlTextChange:(id _Nullable)sender;
- (void)UX3TextControlRightButtonClick:(id _Nullable)sender;
- (void)UX3TextControlLeftButtonClick:(id _Nullable)sender;
@end


SWIFT_CLASS("_TtC4x3UI7XibView")
@interface XibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
#ifndef X3UI_SWIFT_H
#define X3UI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="x3UI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, ControlEventDataType, open) {
  ControlEventDataTypeNone = -1,
  ControlEventDataTypeBool = 1,
  ControlEventDataTypeInt = 2,
  ControlEventDataTypeString = 3,
  ControlEventDataTypeEnumiratedString = 4,
  ControlEventDataTypeObject = 21,
};


SWIFT_PROTOCOL("_TtP4x3UI20ControlEventDelegate_")
@protocol ControlEventDelegate
@optional
- (void)controlEvent:(id _Nullable)sender event:(id _Nullable)event;
@end

@class NSLayoutConstraint;

@interface NSLayoutAnchor<AnchorType> (SWIFT_EXTENSION(x3UI))
- (NSLayoutConstraint * _Nonnull)constraintWithEqualTo:(NSLayoutAnchor<AnchorType> * _Nonnull)anchor constant:(CGFloat)c isActive:(BOOL)isActive SWIFT_WARN_UNUSED_RESULT;
@end


@class Drawing;
@class Animating;

SWIFT_CLASS("_TtC4x3UI18ToolTipPreferences")
@interface ToolTipPreferences : NSObject
@property (nonatomic, strong) Drawing * _Nonnull drawing;
@property (nonatomic, strong) Animating * _Nonnull animating;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Arrow;
@class Bubble;
@class Title;
@class Message;
@class Button;
@class Background;

SWIFT_CLASS("_TtCC4x3UI18ToolTipPreferences7Drawing")
@interface Drawing : NSObject
@property (nonatomic, strong) Arrow * _Nonnull arrow;
@property (nonatomic, strong) Bubble * _Nonnull bubble;
@property (nonatomic, strong) Title * _Nonnull title;
@property (nonatomic, strong) Message * _Nonnull message;
@property (nonatomic, strong) Button * _Nonnull button;
@property (nonatomic, strong) Background * _Nonnull background;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing5Arrow")
@interface Arrow : NSObject
@property (nonatomic) CGSize size;
@property (nonatomic) CGFloat tipCornerRadius;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class Border;

SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing6Bubble")
@interface Bubble : NSObject
@property (nonatomic) CGFloat inset;
@property (nonatomic) CGFloat spacing;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat maxWidth;
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull gradientLocations;
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull gradientColors;
@property (nonatomic, strong) Border * _Nonnull border;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCCC4x3UI18ToolTipPreferences7Drawing6Bubble6Border")
@interface Border : NSObject
@property (nonatomic, strong) UIColor * _Nullable color;
@property (nonatomic) CGFloat width;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIFont;

SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing5Title")
@interface Title : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing7Message")
@interface Message : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing6Button")
@interface Button : NSObject
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCCC4x3UI18ToolTipPreferences7Drawing10Background")
@interface Background : NSObject
@property (nonatomic, strong) UIColor * _Nonnull color;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtCC4x3UI18ToolTipPreferences9Animating")
@interface Animating : NSObject
@property (nonatomic) CGAffineTransform dismissTransform;
@property (nonatomic) CGAffineTransform showInitialTransform;
@property (nonatomic) CGAffineTransform showFinalTransform;
@property (nonatomic) CGFloat springDamping;
@property (nonatomic) CGFloat springVelocity;
@property (nonatomic) CGFloat showInitialAlpha;
@property (nonatomic) CGFloat dismissFinalAlpha;
@property (nonatomic) NSTimeInterval showDuration;
@property (nonatomic) NSTimeInterval dismissDuration;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@class NSString;
enum ArrowPosition : NSInteger;
@protocol UIX3ToolTipDelegate;

@interface UIBarItem (SWIFT_EXTENSION(x3UI))
- (void)showToolTipWithIdentifier:(NSString * _Nonnull)identifier title:(NSString * _Nullable)title message:(NSString * _Nonnull)message button:(NSString * _Nullable)button arrowPosition:(enum ArrowPosition)arrowPosition preferences:(ToolTipPreferences * _Nonnull)preferences delegate:(id <UIX3ToolTipDelegate> _Nullable)delegate;
@end


@class NSCoder;

SWIFT_CLASS("_TtC4x3UI29UIBaseNavigationBarButtonItem")
@interface UIBaseNavigationBarButtonItem : UIBarButtonItem
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4x3UI26UIBaseNavigationTitleLabel")
@interface UIBaseNavigationTitleLabel : UILabel
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4x3UI25UIBaseNavigationTitleView")
@interface UIBaseNavigationTitleView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end













@interface UIView (SWIFT_EXTENSION(x3UI))
- (void)showToolTipWithIdentifier:(NSString * _Nonnull)identifier title:(NSString * _Nullable)title message:(NSString * _Nonnull)message button:(NSString * _Nullable)button arrowPosition:(enum ArrowPosition)arrowPosition preferences:(ToolTipPreferences * _Nonnull)preferences delegate:(id <UIX3ToolTipDelegate> _Nullable)delegate;
@end

@class UIViewController;

@interface UIView (SWIFT_EXTENSION(x3UI))
@property (nonatomic, readonly, strong) UIViewController * _Nullable parentViewController;
@end





SWIFT_CLASS("_TtC4x3UI12UIViewBorder")
@interface UIViewBorder : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIViewController (SWIFT_EXTENSION(x3UI))
+ (nonnull instancetype)fromNib SWIFT_WARN_UNUSED_RESULT;
@end

@class UIAlertAction;
@class UITextField;
@class UIAlertController;

@interface UIViewController (SWIFT_EXTENSION(x3UI))
- (void)showAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message buttonTitle:(NSString * _Nonnull)buttonTitle handler:(void (^ _Nullable)(UIAlertAction * _Nonnull))handler;
- (void)showYesNoAlertWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message yesTitle:(NSString * _Nonnull)yesTitle noTitle:(NSString * _Nonnull)noTitle yesHandler:(void (^ _Nullable)(UIAlertAction * _Nonnull))yesHandler noHandler:(void (^ _Nullable)(UIAlertAction * _Nonnull))noHandler;
- (void)showAlertWithTextFieldWithTitle:(NSString * _Nonnull)title message:(NSString * _Nonnull)message textFieldConfiguration:(void (^ _Nullable)(UITextField * _Nonnull))textFieldConfiguration confirmButtonTitle:(NSString * _Nonnull)confirmButtonTitle handler:(void (^ _Nonnull)(UIAlertController * _Nullable))handler;
- (void)showPopover:(UIViewController * _Nonnull)viewController sourceRect:(CGRect)sourceRect with:(CGSize)size direction:(UIPopoverArrowDirection)direction;
- (void)showPopover:(UIViewController * _Nonnull)viewController barButton:(UIBarButtonItem * _Nonnull)barButton with:(CGSize)size direction:(UIPopoverArrowDirection)direction;
@end

@class NSBundle;

IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI23UIX3AlertViewController")
@interface UIX3AlertViewController : UIViewController
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLayoutSubviews;
- (void)dismissAlertView;
@end

@class UX3CustomButton;

SWIFT_PROTOCOL("_TtP4x3UI31UIX3AlertViewControllerDelegate_")
@protocol UIX3AlertViewControllerDelegate
@optional
- (void)alertViewWithSender:(UIX3AlertViewController * _Nonnull)sender buttonType:(NSInteger)buttonType buttonCreate:(UX3CustomButton * _Nullable)buttonCreate;
- (void)alertViewWithSender:(UIX3AlertViewController * _Nonnull)sender buttonType:(NSInteger)buttonType buttonClick:(UX3CustomButton * _Nullable)buttonClick;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI13UIX3TextField")
@interface UIX3TextField : UITextField
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@property (nonatomic, strong) UIColor * _Nullable textColor;
@property (nonatomic, strong) UIFont * _Nullable font;
@property (nonatomic, copy) NSString * _Nullable placeholder;
@property (nonatomic, strong) UIColor * _Null_unspecified tintColor;
- (void)textFieldDidChange;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)rightViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)leftViewRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (void)drawTextInRect:(CGRect)rect;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI20UIX3CaptionTextField")
@interface UIX3CaptionTextField : UIX3TextField
@property (nonatomic, copy) NSString * _Nullable placeholder;
- (CGRect)placeholderRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)textRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (CGRect)editingRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI14UIX3CustomView")
@interface UIX3CustomView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI15UIX3CaptionView")
@interface UIX3CaptionView : UIX3CustomView
- (void)layoutSubviews;
@property (nonatomic, copy) IBInspectable NSString * _Nullable caption;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable font;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIX3CaptionView (SWIFT_EXTENSION(x3UI)) <UITextViewDelegate>
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI20UIX3CustomBorderView")
@interface UIX3CustomBorderView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI22UIX3CustomBorderedView")
@interface UIX3CustomBorderedView : UIView
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITraitCollection;

IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI24UIX3CustomViewController")
@interface UIX3CustomViewController : UIViewController
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull backgroundColor;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)traitCollectionDidChange:(UITraitCollection * _Nullable)previousTraitCollection;
- (void)deviceRotateEventWithOrientation:(UIDeviceOrientation)orientation isLandscape:(BOOL)isLandscape;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP4x3UI32UIX3CustomViewControllerDelegate_")
@protocol UIX3CustomViewControllerDelegate
@optional
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender;
- (void)customViewControllerWithWillSetupFor:(UIX3CustomViewController * _Nonnull)sender;
- (NSString * _Nonnull)customViewControllerWithTitleFor:(UIX3CustomViewController * _Nonnull)sender SWIFT_WARN_UNUSED_RESULT;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender keyboardRect:(id _Nullable)keyboardRect duration:(double)duration options:(id _Nullable)options;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender keyboardTopPosition:(CGFloat)keyboardTopPosition duration:(double)duration options:(id _Nullable)options;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender statusBarStyle:(UIStatusBarStyle)statusBarStyle;
- (void)customViewControllerWithSender:(UIX3CustomViewController * _Nonnull)sender orientation:(UIDeviceOrientation)orientation isLandscape:(BOOL)isLandscape;
@end

@class NSTextContainer;
@class NSAttributedString;
@class UIImage;

/// Text field with support for multiple lines.
/// note:
/// Under the hood this is just a <code>UITextView</code> which aims to provide
/// many of the functionalities currently available in the <code>UITextField</code> class.
/// Currently the following functionalities are supported:
/// <ul>
///   <li>
///     Multiple lines
///   </li>
///   <li>
///     Customizable left view
///   </li>
///   <li>
///     Customizable placeholder
///   </li>
/// </ul>
/// todo:
/// The following features are still missing:
/// <ul>
///   <li>
///     Add support for displaying a right view
///   </li>
///   <li>
///     Configure when left/right views will be shown using <code>UITextField.leftViewMode</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC4x3UI22UIX3MultilineTextField")
@interface UIX3MultilineTextField : UITextView
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Null_unspecified text;
@property (nonatomic, strong) NSAttributedString * _Null_unspecified attributedText;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
/// Convenience property to set an image directly instead of a left view
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftImage;
- (void)willMoveToSuperview:(UIView * _Nullable)newSuperview;
@end

@class UIGestureRecognizer;

SWIFT_CLASS("_TtC4x3UI18UIX3SegmentControl")
@interface UIX3SegmentControl : UISegmentedControl
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable tintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable backgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable foregroundColor;
@property (nonatomic, strong) IBInspectable UIFont * _Nullable font;
- (void)layoutSubviews;
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer * _Nonnull)gestureRecognizer SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithItems:(NSArray * _Nullable)items OBJC_DESIGNATED_INITIALIZER;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI12UIX3TextView")
@interface UIX3TextView : UIX3CustomView <UITextViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable textColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable placeholderTextColor;
@property (nonatomic, strong) IBInspectable UIColor * _Null_unspecified tintColor;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable leftButtonImage;
@property (nonatomic) IBInspectable CGFloat leftButtonImageOffset;
@property (nonatomic) IBInspectable CGFloat leftButtonLeftOffset;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable rightButtonImage;
@property (nonatomic) IBInspectable CGFloat rightButtonImageOffset;
@property (nonatomic) IBInspectable CGFloat rightButtonRightOffset;
@property (nonatomic, copy) IBInspectable NSString * _Nullable text;
@property (nonatomic, copy) IBInspectable NSString * _Nullable placeholder;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
- (void)layoutSubviews;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
@end


SWIFT_CLASS("_TtC4x3UI11UIX3ToolTip")
@interface UIX3ToolTip : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, ArrowPosition, open) {
  ArrowPositionTop = 0,
  ArrowPositionRight = 1,
  ArrowPositionBottom = 2,
  ArrowPositionLeft = 3,
};


SWIFT_PROTOCOL("_TtP4x3UI19UIX3ToolTipDelegate_")
@protocol UIX3ToolTipDelegate
- (void)toolTipViewDidAppearFor:(NSString * _Nonnull)identifier;
- (void)toolTipViewDidDisappearFor:(NSString * _Nonnull)identifier with:(NSTimeInterval)timeInterval;
@end


SWIFT_CLASS("_TtC4x3UI11UIX3XibView")
@interface UIX3XibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI15UX3CustomButton")
@interface UX3CustomButton : UIButton
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (CGRect)imageRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalForegroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable normalBorderColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedForegroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nullable selectedBorderColor;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI16UX3RoundedButton")
@interface UX3RoundedButton : UIButton
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull normalColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedColor;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic, getter=isHighlighted) BOOL highlighted;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC4x3UI25UX3SliderIndicatorControl")
@interface UX3SliderIndicatorControl : UIControl
@property (nonatomic) IBInspectable CGFloat animationDuration;
@property (nonatomic) IBInspectable CGFloat thumbViewAlpha;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull segmentColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull thumbColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull segmentSelectedColor;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_PROTOCOL("_TtP4x3UI22UX3TextControlDelegate_")
@protocol UX3TextControlDelegate
@optional
- (void)UX3TextControlTextChange:(id _Nullable)sender;
- (void)UX3TextControlRightButtonClick:(id _Nullable)sender;
- (void)UX3TextControlLeftButtonClick:(id _Nullable)sender;
@end


SWIFT_CLASS("_TtC4x3UI7XibView")
@interface XibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
